server:
  port: 8081
spring:
    cloud:
        config:
            server:
                git:
                    default-label: SCRUM-16-crear-rol
                    uri: https://github.com/GeraldineBecerra/topDeck
                    search-paths: config-data
    application:
        name: config-service