server:
  port: 8081
spring:
    cloud:
        config:
            server:
                git:
                    default-label: SCRUM-12-crear-medio-de-pago
                    uri: https://github.com/Deimonlay13/topDeck
                    search-paths: config-data
    application:
        name: config-service